plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rails
  - rubocop-capybara
  - rubocop-performance
  - rubocop-factory_bot

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache_rails_dir
  MaxFilesInCache: 4000
  Exclude:
    - db/schema.rb
  NewCops: enable

#################### Style ###########################

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

##################### Metrics ##################################

##################### Rails ##################################

##################### RSpec ##################################

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/ability/*"

